#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 20 10:15:10 2023

@author: sadegh
"""
#%% import liberaries
import numpy as np
import matplotlib.pyplot as plt
import utm
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib
import pygimli as pg
import geopandas as gpd
import fiona
from pygimli.viewer.mpl import drawModel1D
import pandas as pd
# %% Save data as a multipage pdf 

# import data
farmName = 'Brodowin Hoben'
data = np.loadtxt(f'{farmName} farm_data.csv', delimiter=';')
Eutm, Nutm, H, Gamma = data[:,0] , data[:,1], data[:,2], data[:,8]
Rho1, Rho2, Rho3, Rho4, Rho6 = data[:, 3],data[:, 4],data[:, 5],data[:, 6],data[:, 7]
refPoints = pd.read_csv(f'{farmName} farm_refPoints.csv', delimiter=';')
refEutm, refNutm = refPoints['E'] , refPoints['N']
RhoData = data[:, 3:8]

with PdfPages(f'{farmName} mapped-data-multipage_pdf_.pdf') as pdf:
    # Orthophoto map
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.plot(Eutm, Nutm, ".", markersize=0.5)
    ax.set_aspect(1.0)
    ax.grid()
    plt.title('Digital-Orthophoto', fontsize=10)
    plt.suptitle(f'{farmName} farm', fontsize=14)
    plt.xlabel('Easting [m]')
    plt.ylabel('Northing [m]')
    plt.yticks(rotation=45, ha='right')
    plt.xticks(rotation=45, ha='right')
    plt.axis("equal")
    pg.viewer.mpl.underlayBKGMap(ax, mode='DOP', utmzone=33, epsg=0, uuid='8102b4d5-7fdb-a6a0-d710-890a1caab5c3', usetls=False, origin=None) 
    # plt.savefig(f'Digital-Orthophoto {farmName} farm.png', dpi=200)
    plt.savefig(pdf, format='pdf') 
            
    # Elevation  map
    fig=plt.figure(figsize=(8, 6))      
    ax2 = plt.scatter(Eutm, Nutm, s=0.5, c=H, cmap='plasma', vmin=np.min(H), vmax=np.max(H))
    clb = plt.colorbar(ax2)
    clb.ax.set_title('[m]',fontsize=8)
    plt.axis("equal")
    plt.title('Elevation', fontsize=10)
    plt.suptitle(f'{farmName} farm', fontsize=14)
    plt.xlabel('Easting [m]')
    plt.ylabel('Northing [m]')
    plt.yticks(rotation=45, ha='right')
    plt.xticks(rotation=45, ha='right')
    # plt.savefig(f'{farmName} farm - Elevation.png', dpi=200)
    # plt.savefig(f'{farmName} farm - Elevation.pdf')

    plt.savefig(pdf, format='pdf') 
    
    # Gamma map
    fig=plt.figure(figsize=(8, 6))      
    ax2 = plt.scatter(Eutm, Nutm, s=0.5, c=Gamma, cmap='plasma', vmin=0.4, vmax=1.6)
    clb = plt.colorbar(ax2)
    clb.ax.set_title('[?]',fontsize=8)
    plt.axis("equal")
    plt.title('Gamma', fontsize=10)
    plt.suptitle(f'{farmName} farm', fontsize=14)
    plt.xlabel('Easting [m]')
    plt.ylabel('Northing [m]')
    plt.xticks(rotation=45, ha='right')    
    plt.yticks(rotation=45, ha='right')
    # plt.savefig(f'{farmName} farm - Gamma.png', dpi=200)
    # plt.savefig(f'{farmName} farm - Gamma.pdf')

    plt.savefig(pdf, format='pdf')     
    
    # Rho maps
    for col in range(RhoData.shape[1]):
        Rho_i = col+1
        Rhoi =RhoData[:,col]
        norm = matplotlib.colors.LogNorm(vmin=10, vmax=1000, clip=False)
        fig=plt.figure(figsize=(8, 6))
        ax1 = plt.scatter(Eutm, Nutm, s=0.5, c=RhoData[:,col], cmap='Spectral_r', norm=norm)
        clb = fig.colorbar(ax1)
        clb.ax.set_title('(ohm m)',fontsize=8)
        plt.axis("equal")
        plt.title(f'Rho{Rho_i}', fontsize=10)
        plt.suptitle(f'{farmName} farm', fontsize=14)
        plt.xlabel('Easting [m]')
        plt.ylabel('Northing [m]')
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=45, ha='right')
        ax2 = plt.scatter(refEutm, refNutm, s=5.5, label="Reference points") #Ref Points
        refName = refPoints['Name'].astype(int) # refPoint names
        for i, txt in enumerate(refName):
            plt.annotate(txt, (refEutm[i], refNutm[i]), fontsize=7)
            plt.legend(loc="upper left")

        # plt.savefig(f'{farmName} farm - Rho{Rho_i}.png', dpi=200)
        # plt.savefig(f'{farmName} farm - Rho{Rho_i}.pdf')
        plt.savefig(pdf, format='pdf')   
    
    # histogram of data distribution (log)
    RhoData = np.column_stack((Rho1, Rho2, Rho3, Rho4, Rho6))
    num_bins = 100
    fig=plt.figure(figsize=(8, 6))
    c = 1  # initialize plot counter
    for cols in range(RhoData.shape[1]):
        Rho_i = cols+1
        Rhoi =RhoData[:,cols]
        ax1 = plt.subplot(2, 3, 1)
        ax2 = plt.subplot(2, 3, c, sharex=ax1, sharey=ax1)
        counts, bins = np.histogram(np.log10(RhoData[:,cols]), bins=num_bins)
        ax3 = plt.stairs(counts, bins)
        ax4 = plt.hist(bins[:-1], bins, weights=counts, alpha=0.7)
        plt.suptitle(f'Data Frequency Distributions - {farmName} farm', fontsize=15, y=0.98)
        plt.title(f'Rho{Rho_i}', fontsize=12)
        plt.xlabel('log Resistivity')
        plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.25, hspace=0.4)
        plt.grid()
        # plt.ylabel('Data frequency')
        # plt.savefig(f'{farmName} farm - hist {Rho_i}.png', dpi=200)
        # plt.savefig(f'{farmName} farm - hist {Rho_i}.pdf') 
        c=c+1

    plt.savefig(pdf, format='pdf') 
        # Axes.set_adjustable({'box', 'datalim'}, share=True)
        
# %% Find nearest dataPoints to refPoints
meanDataVal =[]
refpoints = f'{farmName} farm_refPoints.csv'
RefPoints = pd.read_csv(refpoints, delimiter=";")

with PdfPages(f'{farmName} DataDistNearestPoints.pdf') as pdf:
    for i , point in RefPoints.iterrows():
        array = data
        dist = np.sqrt((array[:,0]-point['E'])**2+(array[:,1]-point['N'])**2)

        distToRef = 15
        nearestArray = np.nonzero(dist<distToRef)[0] # return indices of the elements that are non-zero
        dataNearest = data[nearestArray]   # data of individual closest points
        
        fig, ((ax1,ax2,a3), (ax4,ax5, ax6)) = plt.subplots(2, 3, figsize=(15, 10))
        ax1.semilogy(Rho1[nearestArray], marker='.', label='Rho1')
        ax1.set_title('Rho1')
        ax1.grid()
        fig.suptitle(f'Data distribution of points closer than {distToRef}m to refrence point {point[0]}', fontsize=16)

        ax2.semilogy(Rho2[nearestArray], linestyle=None, marker='.', label='Rho2')
        ax2.set_title('Rho2')
        ax2.grid()
        
        ax4.semilogy(Rho3[nearestArray], linestyle=None, marker='.', label='Rho3')
        ax4.set_title('Rho3')
        ax4.grid()
        
        ax5.semilogy(Rho4[nearestArray], linestyle=None, marker='.', label='Rho4')
        ax5.set_title('Rho4')
        ax5.grid()
                      
        ax6.semilogy(Rho6[nearestArray], linestyle=None, marker='.', label='Rho6')
        ax6.set_title('Rho6')
        ax6.grid()
        
        # ax3.plot(Eutm[nearestAray], Nutm[nearestAray], "x", label='Nearest Points')
        # ax3.plot(point[1], point[2], "o", label=f'Reference Point {point[0]}')
        # ax3.set_title('Nearest points location')
    
        plt.savefig(pdf, format='pdf') 

        # fig2, ax = plt.subplots()
        # matplotlib.pyplot.legend()
        # ax.plot(Eutm[nearestAray], Nutm[nearestAray], "x", label='Nearest Points')
        # ax.plot(point[1], point[2], "o", label=f'Reference Point {point[0]}')
        # ax.axis('equal')
        # leg = ax.legend();
#%% Histogram of Rho in the nearest points 
with PdfPages(f'{farmName} DataHistogramNearestPoints.pdf') as pdf:
    for i , point in RefPoints.iterrows():
        array = data
        dist = np.sqrt((array[:,0]-point['E'])**2+(array[:,1]-point['N'])**2)
        distToRef = 15
        nearestAray = np.nonzero(dist<distToRef)[0] # return indices of the elements that are non-zero
        Data_NearestPoints = np.column_stack(((Eutm[nearestAray]), (Nutm[nearestAray]), \
                                  (Rho1[nearestAray]), (Rho2[nearestAray]), \
                                  (Rho3[nearestAray]), (Rho4[nearestAray]), \
                                  (Rho6[nearestAray]), 
                                  (Gamma[nearestAray]))) 
        # print(point[0], nearestAray.shape, Data_NearestPoints)
          
        Rho_Nearest = Data_NearestPoints[:, 2:7] # Rho of individual closest points
        num_bins = 25
        fig=plt.figure(figsize=(8, 6))
        fig.text(0.5, 0.04, 'log Resistivity', ha='center')
        fig.text(0.04, 0.5, '', va='center', rotation='vertical')
        c = 1  # initialize plot counter
        for cols in range(Rho_Nearest.shape[1]):
            ### plot histogram
            Rho_i = cols+1
            Rhoi =Rho_Nearest[:,cols]
            # print(f'mean Rho{Rho_i} = ', np.round(np.mean(Rhoi),2),  f' \ std Rho{Rho_i} = ', np.round(np.std(Rhoi),2))
            ax1 = plt.subplot(2, 3, 1)
            ax2 = plt.subplot(2, 3, c, sharex=ax1, sharey=ax1)
            counts, bins = np.histogram(np.log10(Rhoi), bins=num_bins)
            ax3 = plt.stairs(counts, bins)
            ax4 = plt.hist(bins[:-1], bins, weights=counts, alpha=0.7)
            plt.suptitle(f'Distribution of the Nearest Data to refrence point {point[0]}- {farmName} farm', fontsize=15, y=0.98)
            plt.title(f'Rho{Rho_i}', fontsize=12)
            # plt.xlabel('log Resistivity')
            plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.25, hspace=0.7)
            # plt.text(1, -1.5, ('mean = ', np.round(np.mean(Rhoi),2)), fontsize=8)    
            # plt.text(1, -2.5, (' std  = ', np.round(np.std(Rhoi),2)), fontsize=8)    
            plt.grid()
            c=c+1
           
        plt.savefig(pdf, format='pdf') 
